[2021-11-18 10:03:26,364] {processor.py:163} INFO - Started process (PID=2774) to work on /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:03:26,367] {processor.py:625} INFO - Processing file /opt/airflow/dags/example_twitter_dag.py for tasks to queue
[2021-11-18 10:03:26,368] {logging_mixin.py:109} INFO - [2021-11-18 10:03:26,368] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:03:26,420] {logging_mixin.py:109} INFO - [2021-11-18 10:03:26,413] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2021-11-18 10:03:26,464] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:03:26,486] {processor.py:171} INFO - Processing /opt/airflow/dags/example_twitter_dag.py took 0.131 seconds
[2021-11-18 10:03:59,128] {processor.py:163} INFO - Started process (PID=2830) to work on /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:03:59,132] {processor.py:625} INFO - Processing file /opt/airflow/dags/example_twitter_dag.py for tasks to queue
[2021-11-18 10:03:59,142] {logging_mixin.py:109} INFO - [2021-11-18 10:03:59,142] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:03:59,206] {logging_mixin.py:109} INFO - [2021-11-18 10:03:59,202] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2021-11-18 10:03:59,263] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:03:59,282] {processor.py:171} INFO - Processing /opt/airflow/dags/example_twitter_dag.py took 0.167 seconds
[2021-11-18 10:04:29,500] {processor.py:163} INFO - Started process (PID=2884) to work on /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:04:29,504] {processor.py:625} INFO - Processing file /opt/airflow/dags/example_twitter_dag.py for tasks to queue
[2021-11-18 10:04:29,508] {logging_mixin.py:109} INFO - [2021-11-18 10:04:29,508] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:04:29,608] {logging_mixin.py:109} INFO - [2021-11-18 10:04:29,595] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2021-11-18 10:04:29,715] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:04:29,811] {processor.py:171} INFO - Processing /opt/airflow/dags/example_twitter_dag.py took 0.320 seconds
[2021-11-18 10:05:00,014] {processor.py:163} INFO - Started process (PID=2938) to work on /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:05:00,017] {processor.py:625} INFO - Processing file /opt/airflow/dags/example_twitter_dag.py for tasks to queue
[2021-11-18 10:05:00,018] {logging_mixin.py:109} INFO - [2021-11-18 10:05:00,018] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:05:00,038] {logging_mixin.py:109} INFO - [2021-11-18 10:05:00,036] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2021-11-18 10:05:00,058] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:05:00,072] {processor.py:171} INFO - Processing /opt/airflow/dags/example_twitter_dag.py took 0.063 seconds
[2021-11-18 10:05:30,150] {processor.py:163} INFO - Started process (PID=2994) to work on /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:05:30,152] {processor.py:625} INFO - Processing file /opt/airflow/dags/example_twitter_dag.py for tasks to queue
[2021-11-18 10:05:30,154] {logging_mixin.py:109} INFO - [2021-11-18 10:05:30,154] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:05:30,174] {logging_mixin.py:109} INFO - [2021-11-18 10:05:30,172] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2021-11-18 10:05:30,191] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:05:30,203] {processor.py:171} INFO - Processing /opt/airflow/dags/example_twitter_dag.py took 0.059 seconds
[2021-11-18 10:06:00,620] {processor.py:163} INFO - Started process (PID=3050) to work on /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:06:00,623] {processor.py:625} INFO - Processing file /opt/airflow/dags/example_twitter_dag.py for tasks to queue
[2021-11-18 10:06:00,625] {logging_mixin.py:109} INFO - [2021-11-18 10:06:00,624] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:06:00,646] {logging_mixin.py:109} INFO - [2021-11-18 10:06:00,644] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2021-11-18 10:06:00,668] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:06:00,678] {processor.py:171} INFO - Processing /opt/airflow/dags/example_twitter_dag.py took 0.064 seconds
[2021-11-18 10:06:30,791] {processor.py:163} INFO - Started process (PID=3107) to work on /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:06:30,796] {processor.py:625} INFO - Processing file /opt/airflow/dags/example_twitter_dag.py for tasks to queue
[2021-11-18 10:06:30,804] {logging_mixin.py:109} INFO - [2021-11-18 10:06:30,804] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:06:30,880] {logging_mixin.py:109} INFO - [2021-11-18 10:06:30,858] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2021-11-18 10:06:31,276] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:06:31,690] {processor.py:171} INFO - Processing /opt/airflow/dags/example_twitter_dag.py took 0.908 seconds
[2021-11-18 10:07:02,393] {processor.py:163} INFO - Started process (PID=3165) to work on /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:07:02,425] {processor.py:625} INFO - Processing file /opt/airflow/dags/example_twitter_dag.py for tasks to queue
[2021-11-18 10:07:02,434] {logging_mixin.py:109} INFO - [2021-11-18 10:07:02,434] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:07:02,605] {logging_mixin.py:109} INFO - [2021-11-18 10:07:02,594] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2021-11-18 10:07:02,821] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:07:02,844] {processor.py:171} INFO - Processing /opt/airflow/dags/example_twitter_dag.py took 0.466 seconds
[2021-11-18 10:07:33,065] {processor.py:163} INFO - Started process (PID=3223) to work on /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:07:33,069] {processor.py:625} INFO - Processing file /opt/airflow/dags/example_twitter_dag.py for tasks to queue
[2021-11-18 10:07:33,079] {logging_mixin.py:109} INFO - [2021-11-18 10:07:33,079] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:07:33,124] {logging_mixin.py:109} INFO - [2021-11-18 10:07:33,112] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2021-11-18 10:07:33,169] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:07:33,194] {processor.py:171} INFO - Processing /opt/airflow/dags/example_twitter_dag.py took 0.148 seconds
[2021-11-18 10:08:03,680] {processor.py:163} INFO - Started process (PID=3268) to work on /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:08:03,690] {processor.py:625} INFO - Processing file /opt/airflow/dags/example_twitter_dag.py for tasks to queue
[2021-11-18 10:08:03,693] {logging_mixin.py:109} INFO - [2021-11-18 10:08:03,692] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:08:03,747] {logging_mixin.py:109} INFO - [2021-11-18 10:08:03,741] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2021-11-18 10:08:03,846] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:08:03,869] {processor.py:171} INFO - Processing /opt/airflow/dags/example_twitter_dag.py took 0.206 seconds
[2021-11-18 10:08:34,123] {processor.py:163} INFO - Started process (PID=3325) to work on /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:08:34,127] {processor.py:625} INFO - Processing file /opt/airflow/dags/example_twitter_dag.py for tasks to queue
[2021-11-18 10:08:34,129] {logging_mixin.py:109} INFO - [2021-11-18 10:08:34,129] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:08:34,168] {logging_mixin.py:109} INFO - [2021-11-18 10:08:34,164] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2021-11-18 10:08:34,191] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:08:34,203] {processor.py:171} INFO - Processing /opt/airflow/dags/example_twitter_dag.py took 0.088 seconds
[2021-11-18 10:09:04,733] {processor.py:163} INFO - Started process (PID=3380) to work on /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:09:04,740] {processor.py:625} INFO - Processing file /opt/airflow/dags/example_twitter_dag.py for tasks to queue
[2021-11-18 10:09:04,741] {logging_mixin.py:109} INFO - [2021-11-18 10:09:04,741] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:09:04,774] {logging_mixin.py:109} INFO - [2021-11-18 10:09:04,768] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2021-11-18 10:09:04,801] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:09:04,809] {processor.py:171} INFO - Processing /opt/airflow/dags/example_twitter_dag.py took 0.082 seconds
[2021-11-18 10:09:35,547] {processor.py:163} INFO - Started process (PID=3439) to work on /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:09:35,554] {processor.py:625} INFO - Processing file /opt/airflow/dags/example_twitter_dag.py for tasks to queue
[2021-11-18 10:09:35,564] {logging_mixin.py:109} INFO - [2021-11-18 10:09:35,564] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:09:35,708] {logging_mixin.py:109} INFO - [2021-11-18 10:09:35,675] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2021-11-18 10:09:35,914] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:09:35,936] {processor.py:171} INFO - Processing /opt/airflow/dags/example_twitter_dag.py took 0.418 seconds
[2021-11-18 10:10:06,624] {processor.py:163} INFO - Started process (PID=3493) to work on /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:10:06,629] {processor.py:625} INFO - Processing file /opt/airflow/dags/example_twitter_dag.py for tasks to queue
[2021-11-18 10:10:06,631] {logging_mixin.py:109} INFO - [2021-11-18 10:10:06,631] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:10:06,683] {logging_mixin.py:109} INFO - [2021-11-18 10:10:06,669] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2021-11-18 10:10:06,726] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:10:06,753] {processor.py:171} INFO - Processing /opt/airflow/dags/example_twitter_dag.py took 0.142 seconds
[2021-11-18 10:10:37,004] {processor.py:163} INFO - Started process (PID=3550) to work on /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:10:37,008] {processor.py:625} INFO - Processing file /opt/airflow/dags/example_twitter_dag.py for tasks to queue
[2021-11-18 10:10:37,016] {logging_mixin.py:109} INFO - [2021-11-18 10:10:37,012] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:10:37,160] {logging_mixin.py:109} INFO - [2021-11-18 10:10:37,150] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2021-11-18 10:10:37,230] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:10:37,248] {processor.py:171} INFO - Processing /opt/airflow/dags/example_twitter_dag.py took 0.272 seconds
[2021-11-18 10:11:07,527] {processor.py:163} INFO - Started process (PID=3608) to work on /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:11:07,538] {processor.py:625} INFO - Processing file /opt/airflow/dags/example_twitter_dag.py for tasks to queue
[2021-11-18 10:11:07,543] {logging_mixin.py:109} INFO - [2021-11-18 10:11:07,543] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:11:07,604] {logging_mixin.py:109} INFO - [2021-11-18 10:11:07,600] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2021-11-18 10:11:07,626] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:11:07,637] {processor.py:171} INFO - Processing /opt/airflow/dags/example_twitter_dag.py took 0.117 seconds
[2021-11-18 10:11:37,759] {processor.py:163} INFO - Started process (PID=3674) to work on /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:11:37,763] {processor.py:625} INFO - Processing file /opt/airflow/dags/example_twitter_dag.py for tasks to queue
[2021-11-18 10:11:37,765] {logging_mixin.py:109} INFO - [2021-11-18 10:11:37,765] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:11:37,789] {logging_mixin.py:109} INFO - [2021-11-18 10:11:37,787] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2021-11-18 10:11:37,807] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:11:37,818] {processor.py:171} INFO - Processing /opt/airflow/dags/example_twitter_dag.py took 0.065 seconds
[2021-11-18 10:12:12,562] {processor.py:163} INFO - Started process (PID=3735) to work on /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:12:12,567] {processor.py:625} INFO - Processing file /opt/airflow/dags/example_twitter_dag.py for tasks to queue
[2021-11-18 10:12:12,577] {logging_mixin.py:109} INFO - [2021-11-18 10:12:12,575] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:12:12,830] {logging_mixin.py:109} INFO - [2021-11-18 10:12:12,774] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2021-11-18 10:12:12,961] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:12:13,000] {processor.py:171} INFO - Processing /opt/airflow/dags/example_twitter_dag.py took 0.627 seconds
[2021-11-18 10:12:43,436] {processor.py:163} INFO - Started process (PID=3792) to work on /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:12:43,440] {processor.py:625} INFO - Processing file /opt/airflow/dags/example_twitter_dag.py for tasks to queue
[2021-11-18 10:12:43,447] {logging_mixin.py:109} INFO - [2021-11-18 10:12:43,447] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:12:43,485] {logging_mixin.py:109} INFO - [2021-11-18 10:12:43,480] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2021-11-18 10:12:43,525] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:12:43,538] {processor.py:171} INFO - Processing /opt/airflow/dags/example_twitter_dag.py took 0.110 seconds
[2021-11-18 10:13:14,007] {processor.py:163} INFO - Started process (PID=3849) to work on /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:13:14,010] {processor.py:625} INFO - Processing file /opt/airflow/dags/example_twitter_dag.py for tasks to queue
[2021-11-18 10:13:14,012] {logging_mixin.py:109} INFO - [2021-11-18 10:13:14,012] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:13:14,063] {logging_mixin.py:109} INFO - [2021-11-18 10:13:14,057] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2021-11-18 10:13:14,093] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:13:14,105] {processor.py:171} INFO - Processing /opt/airflow/dags/example_twitter_dag.py took 0.111 seconds
[2021-11-18 10:13:45,034] {processor.py:163} INFO - Started process (PID=3906) to work on /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:13:45,045] {processor.py:625} INFO - Processing file /opt/airflow/dags/example_twitter_dag.py for tasks to queue
[2021-11-18 10:13:45,047] {logging_mixin.py:109} INFO - [2021-11-18 10:13:45,047] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:13:45,098] {logging_mixin.py:109} INFO - [2021-11-18 10:13:45,094] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2021-11-18 10:13:45,148] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:13:45,172] {processor.py:171} INFO - Processing /opt/airflow/dags/example_twitter_dag.py took 0.150 seconds
[2021-11-18 10:14:15,515] {processor.py:163} INFO - Started process (PID=3962) to work on /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:14:15,519] {processor.py:625} INFO - Processing file /opt/airflow/dags/example_twitter_dag.py for tasks to queue
[2021-11-18 10:14:15,526] {logging_mixin.py:109} INFO - [2021-11-18 10:14:15,526] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:14:15,643] {logging_mixin.py:109} INFO - [2021-11-18 10:14:15,621] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2021-11-18 10:14:15,754] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:14:15,900] {processor.py:171} INFO - Processing /opt/airflow/dags/example_twitter_dag.py took 0.410 seconds
[2021-11-18 10:14:46,164] {processor.py:163} INFO - Started process (PID=4018) to work on /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:14:46,170] {processor.py:625} INFO - Processing file /opt/airflow/dags/example_twitter_dag.py for tasks to queue
[2021-11-18 10:14:46,174] {logging_mixin.py:109} INFO - [2021-11-18 10:14:46,173] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:14:46,210] {logging_mixin.py:109} INFO - [2021-11-18 10:14:46,205] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2021-11-18 10:14:46,240] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:14:46,260] {processor.py:171} INFO - Processing /opt/airflow/dags/example_twitter_dag.py took 0.110 seconds
[2021-11-18 10:15:16,648] {processor.py:163} INFO - Started process (PID=4075) to work on /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:15:16,653] {processor.py:625} INFO - Processing file /opt/airflow/dags/example_twitter_dag.py for tasks to queue
[2021-11-18 10:15:16,656] {logging_mixin.py:109} INFO - [2021-11-18 10:15:16,655] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:15:16,696] {logging_mixin.py:109} INFO - [2021-11-18 10:15:16,689] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2021-11-18 10:15:16,739] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:15:16,777] {processor.py:171} INFO - Processing /opt/airflow/dags/example_twitter_dag.py took 0.148 seconds
[2021-11-18 10:15:47,108] {processor.py:163} INFO - Started process (PID=4131) to work on /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:15:47,111] {processor.py:625} INFO - Processing file /opt/airflow/dags/example_twitter_dag.py for tasks to queue
[2021-11-18 10:15:47,113] {logging_mixin.py:109} INFO - [2021-11-18 10:15:47,113] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:15:47,136] {logging_mixin.py:109} INFO - [2021-11-18 10:15:47,134] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2021-11-18 10:15:47,157] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:15:47,169] {processor.py:171} INFO - Processing /opt/airflow/dags/example_twitter_dag.py took 0.068 seconds
[2021-11-18 10:16:17,748] {processor.py:163} INFO - Started process (PID=4188) to work on /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:16:17,752] {processor.py:625} INFO - Processing file /opt/airflow/dags/example_twitter_dag.py for tasks to queue
[2021-11-18 10:16:17,755] {logging_mixin.py:109} INFO - [2021-11-18 10:16:17,755] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:16:17,785] {logging_mixin.py:109} INFO - [2021-11-18 10:16:17,779] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2021-11-18 10:16:17,814] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:16:17,827] {processor.py:171} INFO - Processing /opt/airflow/dags/example_twitter_dag.py took 0.084 seconds
[2021-11-18 10:16:48,068] {processor.py:163} INFO - Started process (PID=4245) to work on /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:16:48,076] {processor.py:625} INFO - Processing file /opt/airflow/dags/example_twitter_dag.py for tasks to queue
[2021-11-18 10:16:48,079] {logging_mixin.py:109} INFO - [2021-11-18 10:16:48,079] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:16:48,101] {logging_mixin.py:109} INFO - [2021-11-18 10:16:48,098] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2021-11-18 10:16:48,124] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:16:48,137] {processor.py:171} INFO - Processing /opt/airflow/dags/example_twitter_dag.py took 0.077 seconds
[2021-11-18 10:17:18,509] {processor.py:163} INFO - Started process (PID=4309) to work on /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:17:18,512] {processor.py:625} INFO - Processing file /opt/airflow/dags/example_twitter_dag.py for tasks to queue
[2021-11-18 10:17:18,516] {logging_mixin.py:109} INFO - [2021-11-18 10:17:18,515] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:17:18,555] {logging_mixin.py:109} INFO - [2021-11-18 10:17:18,548] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2021-11-18 10:17:18,593] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:17:18,615] {processor.py:171} INFO - Processing /opt/airflow/dags/example_twitter_dag.py took 0.138 seconds
[2021-11-18 10:26:56,144] {processor.py:163} INFO - Started process (PID=65) to work on /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:26:56,168] {processor.py:625} INFO - Processing file /opt/airflow/dags/example_twitter_dag.py for tasks to queue
[2021-11-18 10:26:56,184] {logging_mixin.py:109} INFO - [2021-11-18 10:26:56,183] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:26:56,393] {logging_mixin.py:109} INFO - [2021-11-18 10:26:56,379] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2021-11-18 10:26:56,498] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:26:56,530] {processor.py:171} INFO - Processing /opt/airflow/dags/example_twitter_dag.py took 0.425 seconds
[2021-11-18 10:27:28,677] {processor.py:163} INFO - Started process (PID=119) to work on /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:27:28,695] {processor.py:625} INFO - Processing file /opt/airflow/dags/example_twitter_dag.py for tasks to queue
[2021-11-18 10:27:28,712] {logging_mixin.py:109} INFO - [2021-11-18 10:27:28,701] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:27:28,913] {logging_mixin.py:109} INFO - [2021-11-18 10:27:28,865] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2021-11-18 10:27:29,048] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:27:29,198] {processor.py:171} INFO - Processing /opt/airflow/dags/example_twitter_dag.py took 0.549 seconds
[2021-11-18 10:27:59,814] {processor.py:163} INFO - Started process (PID=166) to work on /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:27:59,818] {processor.py:625} INFO - Processing file /opt/airflow/dags/example_twitter_dag.py for tasks to queue
[2021-11-18 10:27:59,819] {logging_mixin.py:109} INFO - [2021-11-18 10:27:59,819] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:27:59,864] {logging_mixin.py:109} INFO - [2021-11-18 10:27:59,860] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2021-11-18 10:27:59,898] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:27:59,915] {processor.py:171} INFO - Processing /opt/airflow/dags/example_twitter_dag.py took 0.107 seconds
[2021-11-18 10:28:30,548] {processor.py:163} INFO - Started process (PID=238) to work on /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:28:30,555] {processor.py:625} INFO - Processing file /opt/airflow/dags/example_twitter_dag.py for tasks to queue
[2021-11-18 10:28:30,558] {logging_mixin.py:109} INFO - [2021-11-18 10:28:30,558] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:28:30,603] {logging_mixin.py:109} INFO - [2021-11-18 10:28:30,591] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2021-11-18 10:28:30,635] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:28:30,650] {processor.py:171} INFO - Processing /opt/airflow/dags/example_twitter_dag.py took 0.113 seconds
[2021-11-18 10:29:01,402] {processor.py:163} INFO - Started process (PID=274) to work on /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:29:01,442] {processor.py:625} INFO - Processing file /opt/airflow/dags/example_twitter_dag.py for tasks to queue
[2021-11-18 10:29:01,444] {logging_mixin.py:109} INFO - [2021-11-18 10:29:01,444] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:29:01,615] {logging_mixin.py:109} INFO - [2021-11-18 10:29:01,596] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2021-11-18 10:29:01,729] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:29:01,810] {processor.py:171} INFO - Processing /opt/airflow/dags/example_twitter_dag.py took 0.466 seconds
[2021-11-18 10:29:34,807] {processor.py:163} INFO - Started process (PID=321) to work on /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:29:34,833] {processor.py:625} INFO - Processing file /opt/airflow/dags/example_twitter_dag.py for tasks to queue
[2021-11-18 10:29:34,835] {logging_mixin.py:109} INFO - [2021-11-18 10:29:34,835] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:29:34,910] {logging_mixin.py:109} INFO - [2021-11-18 10:29:34,903] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2021-11-18 10:29:34,991] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:29:35,008] {processor.py:171} INFO - Processing /opt/airflow/dags/example_twitter_dag.py took 0.210 seconds
[2021-11-18 10:30:05,264] {processor.py:163} INFO - Started process (PID=375) to work on /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:30:05,267] {processor.py:625} INFO - Processing file /opt/airflow/dags/example_twitter_dag.py for tasks to queue
[2021-11-18 10:30:05,279] {logging_mixin.py:109} INFO - [2021-11-18 10:30:05,278] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:30:05,331] {logging_mixin.py:109} INFO - [2021-11-18 10:30:05,317] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2021-11-18 10:30:05,425] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:30:05,503] {processor.py:171} INFO - Processing /opt/airflow/dags/example_twitter_dag.py took 0.254 seconds
[2021-11-18 10:30:35,732] {processor.py:163} INFO - Started process (PID=430) to work on /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:30:35,738] {processor.py:625} INFO - Processing file /opt/airflow/dags/example_twitter_dag.py for tasks to queue
[2021-11-18 10:30:35,741] {logging_mixin.py:109} INFO - [2021-11-18 10:30:35,741] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:30:35,797] {logging_mixin.py:109} INFO - [2021-11-18 10:30:35,793] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2021-11-18 10:30:35,856] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:30:35,883] {processor.py:171} INFO - Processing /opt/airflow/dags/example_twitter_dag.py took 0.175 seconds
[2021-11-18 10:31:06,056] {processor.py:163} INFO - Started process (PID=484) to work on /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:31:06,065] {processor.py:625} INFO - Processing file /opt/airflow/dags/example_twitter_dag.py for tasks to queue
[2021-11-18 10:31:06,068] {logging_mixin.py:109} INFO - [2021-11-18 10:31:06,068] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:31:06,106] {logging_mixin.py:109} INFO - [2021-11-18 10:31:06,101] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2021-11-18 10:31:06,168] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:31:06,191] {processor.py:171} INFO - Processing /opt/airflow/dags/example_twitter_dag.py took 0.141 seconds
[2021-11-18 10:31:37,293] {processor.py:163} INFO - Started process (PID=539) to work on /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:31:37,308] {processor.py:625} INFO - Processing file /opt/airflow/dags/example_twitter_dag.py for tasks to queue
[2021-11-18 10:31:37,311] {logging_mixin.py:109} INFO - [2021-11-18 10:31:37,310] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:31:37,467] {logging_mixin.py:109} INFO - [2021-11-18 10:31:37,456] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2021-11-18 10:31:37,522] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:31:37,636] {processor.py:171} INFO - Processing /opt/airflow/dags/example_twitter_dag.py took 0.383 seconds
[2021-11-18 10:32:08,568] {processor.py:163} INFO - Started process (PID=593) to work on /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:32:08,571] {processor.py:625} INFO - Processing file /opt/airflow/dags/example_twitter_dag.py for tasks to queue
[2021-11-18 10:32:08,575] {logging_mixin.py:109} INFO - [2021-11-18 10:32:08,574] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:32:08,625] {logging_mixin.py:109} INFO - [2021-11-18 10:32:08,622] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2021-11-18 10:32:08,668] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:32:08,708] {processor.py:171} INFO - Processing /opt/airflow/dags/example_twitter_dag.py took 0.145 seconds
[2021-11-18 10:32:39,616] {processor.py:163} INFO - Started process (PID=648) to work on /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:32:39,674] {processor.py:625} INFO - Processing file /opt/airflow/dags/example_twitter_dag.py for tasks to queue
[2021-11-18 10:32:39,695] {logging_mixin.py:109} INFO - [2021-11-18 10:32:39,694] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:32:40,004] {logging_mixin.py:109} INFO - [2021-11-18 10:32:39,973] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2021-11-18 10:32:40,143] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:32:40,167] {processor.py:171} INFO - Processing /opt/airflow/dags/example_twitter_dag.py took 0.630 seconds
[2021-11-18 10:33:10,741] {processor.py:163} INFO - Started process (PID=704) to work on /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:33:10,754] {processor.py:625} INFO - Processing file /opt/airflow/dags/example_twitter_dag.py for tasks to queue
[2021-11-18 10:33:10,757] {logging_mixin.py:109} INFO - [2021-11-18 10:33:10,757] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:33:10,799] {logging_mixin.py:109} INFO - [2021-11-18 10:33:10,789] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2021-11-18 10:33:10,843] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:33:10,861] {processor.py:171} INFO - Processing /opt/airflow/dags/example_twitter_dag.py took 0.146 seconds
[2021-11-18 10:33:41,460] {processor.py:163} INFO - Started process (PID=761) to work on /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:33:41,465] {processor.py:625} INFO - Processing file /opt/airflow/dags/example_twitter_dag.py for tasks to queue
[2021-11-18 10:33:41,479] {logging_mixin.py:109} INFO - [2021-11-18 10:33:41,479] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:33:41,604] {logging_mixin.py:109} INFO - [2021-11-18 10:33:41,582] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2021-11-18 10:33:41,742] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:33:41,854] {processor.py:171} INFO - Processing /opt/airflow/dags/example_twitter_dag.py took 0.425 seconds
[2021-11-18 10:34:12,042] {processor.py:163} INFO - Started process (PID=818) to work on /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:34:12,046] {processor.py:625} INFO - Processing file /opt/airflow/dags/example_twitter_dag.py for tasks to queue
[2021-11-18 10:34:12,047] {logging_mixin.py:109} INFO - [2021-11-18 10:34:12,047] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:34:12,075] {logging_mixin.py:109} INFO - [2021-11-18 10:34:12,069] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2021-11-18 10:34:12,100] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:34:12,110] {processor.py:171} INFO - Processing /opt/airflow/dags/example_twitter_dag.py took 0.071 seconds
[2021-11-18 10:34:42,882] {processor.py:163} INFO - Started process (PID=874) to work on /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:34:42,885] {processor.py:625} INFO - Processing file /opt/airflow/dags/example_twitter_dag.py for tasks to queue
[2021-11-18 10:34:42,886] {logging_mixin.py:109} INFO - [2021-11-18 10:34:42,886] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:34:42,904] {logging_mixin.py:109} INFO - [2021-11-18 10:34:42,902] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2021-11-18 10:34:42,931] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:34:42,942] {processor.py:171} INFO - Processing /opt/airflow/dags/example_twitter_dag.py took 0.067 seconds
[2021-11-18 10:35:13,610] {processor.py:163} INFO - Started process (PID=929) to work on /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:35:13,620] {processor.py:625} INFO - Processing file /opt/airflow/dags/example_twitter_dag.py for tasks to queue
[2021-11-18 10:35:13,624] {logging_mixin.py:109} INFO - [2021-11-18 10:35:13,623] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:35:13,685] {logging_mixin.py:109} INFO - [2021-11-18 10:35:13,670] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2021-11-18 10:35:13,731] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:35:13,769] {processor.py:171} INFO - Processing /opt/airflow/dags/example_twitter_dag.py took 0.167 seconds
[2021-11-18 10:35:44,200] {processor.py:163} INFO - Started process (PID=984) to work on /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:35:44,202] {processor.py:625} INFO - Processing file /opt/airflow/dags/example_twitter_dag.py for tasks to queue
[2021-11-18 10:35:44,204] {logging_mixin.py:109} INFO - [2021-11-18 10:35:44,203] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:35:44,231] {logging_mixin.py:109} INFO - [2021-11-18 10:35:44,227] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2021-11-18 10:35:44,255] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:35:44,268] {processor.py:171} INFO - Processing /opt/airflow/dags/example_twitter_dag.py took 0.073 seconds
[2021-11-18 10:36:16,261] {processor.py:163} INFO - Started process (PID=1039) to work on /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:36:16,263] {processor.py:625} INFO - Processing file /opt/airflow/dags/example_twitter_dag.py for tasks to queue
[2021-11-18 10:36:16,265] {logging_mixin.py:109} INFO - [2021-11-18 10:36:16,265] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:36:16,286] {logging_mixin.py:109} INFO - [2021-11-18 10:36:16,284] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2021-11-18 10:36:16,325] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:36:16,378] {processor.py:171} INFO - Processing /opt/airflow/dags/example_twitter_dag.py took 0.122 seconds
[2021-11-18 10:36:46,496] {processor.py:163} INFO - Started process (PID=1090) to work on /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:36:46,499] {processor.py:625} INFO - Processing file /opt/airflow/dags/example_twitter_dag.py for tasks to queue
[2021-11-18 10:36:46,503] {logging_mixin.py:109} INFO - [2021-11-18 10:36:46,503] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:36:46,536] {logging_mixin.py:109} INFO - [2021-11-18 10:36:46,525] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2021-11-18 10:36:46,580] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:36:46,615] {processor.py:171} INFO - Processing /opt/airflow/dags/example_twitter_dag.py took 0.127 seconds
[2021-11-18 10:37:20,209] {processor.py:163} INFO - Started process (PID=1144) to work on /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:37:20,212] {processor.py:625} INFO - Processing file /opt/airflow/dags/example_twitter_dag.py for tasks to queue
[2021-11-18 10:37:20,214] {logging_mixin.py:109} INFO - [2021-11-18 10:37:20,214] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:37:20,425] {logging_mixin.py:109} INFO - [2021-11-18 10:37:20,420] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2021-11-18 10:37:20,447] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:37:20,463] {processor.py:171} INFO - Processing /opt/airflow/dags/example_twitter_dag.py took 0.261 seconds
[2021-11-18 10:37:52,467] {processor.py:163} INFO - Started process (PID=1198) to work on /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:37:52,473] {processor.py:625} INFO - Processing file /opt/airflow/dags/example_twitter_dag.py for tasks to queue
[2021-11-18 10:37:52,483] {logging_mixin.py:109} INFO - [2021-11-18 10:37:52,482] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:37:52,674] {logging_mixin.py:109} INFO - [2021-11-18 10:37:52,648] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2021-11-18 10:37:52,767] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:37:52,821] {processor.py:171} INFO - Processing /opt/airflow/dags/example_twitter_dag.py took 0.364 seconds
[2021-11-18 10:38:22,970] {processor.py:163} INFO - Started process (PID=1242) to work on /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:38:22,974] {processor.py:625} INFO - Processing file /opt/airflow/dags/example_twitter_dag.py for tasks to queue
[2021-11-18 10:38:22,980] {logging_mixin.py:109} INFO - [2021-11-18 10:38:22,980] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:38:23,018] {logging_mixin.py:109} INFO - [2021-11-18 10:38:23,015] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2021-11-18 10:38:23,050] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:38:23,072] {processor.py:171} INFO - Processing /opt/airflow/dags/example_twitter_dag.py took 0.124 seconds
[2021-11-18 10:38:53,220] {processor.py:163} INFO - Started process (PID=1310) to work on /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:38:53,225] {processor.py:625} INFO - Processing file /opt/airflow/dags/example_twitter_dag.py for tasks to queue
[2021-11-18 10:38:53,227] {logging_mixin.py:109} INFO - [2021-11-18 10:38:53,227] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:38:53,260] {logging_mixin.py:109} INFO - [2021-11-18 10:38:53,257] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2021-11-18 10:38:53,288] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:38:53,298] {processor.py:171} INFO - Processing /opt/airflow/dags/example_twitter_dag.py took 0.083 seconds
[2021-11-18 10:39:23,743] {processor.py:163} INFO - Started process (PID=1364) to work on /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:39:23,748] {processor.py:625} INFO - Processing file /opt/airflow/dags/example_twitter_dag.py for tasks to queue
[2021-11-18 10:39:23,751] {logging_mixin.py:109} INFO - [2021-11-18 10:39:23,751] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:39:23,877] {logging_mixin.py:109} INFO - [2021-11-18 10:39:23,835] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2021-11-18 10:39:24,041] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:39:24,085] {processor.py:171} INFO - Processing /opt/airflow/dags/example_twitter_dag.py took 0.364 seconds
[2021-11-18 10:39:54,189] {processor.py:163} INFO - Started process (PID=1419) to work on /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:39:54,191] {processor.py:625} INFO - Processing file /opt/airflow/dags/example_twitter_dag.py for tasks to queue
[2021-11-18 10:39:54,193] {logging_mixin.py:109} INFO - [2021-11-18 10:39:54,193] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:39:54,212] {logging_mixin.py:109} INFO - [2021-11-18 10:39:54,210] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2021-11-18 10:39:54,231] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:39:54,242] {processor.py:171} INFO - Processing /opt/airflow/dags/example_twitter_dag.py took 0.059 seconds
[2021-11-18 10:40:24,528] {processor.py:163} INFO - Started process (PID=1472) to work on /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:40:24,535] {processor.py:625} INFO - Processing file /opt/airflow/dags/example_twitter_dag.py for tasks to queue
[2021-11-18 10:40:24,537] {logging_mixin.py:109} INFO - [2021-11-18 10:40:24,537] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:40:24,563] {logging_mixin.py:109} INFO - [2021-11-18 10:40:24,559] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2021-11-18 10:40:24,723] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:40:24,748] {processor.py:171} INFO - Processing /opt/airflow/dags/example_twitter_dag.py took 0.225 seconds
[2021-11-18 10:40:54,958] {processor.py:163} INFO - Started process (PID=1531) to work on /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:40:54,963] {processor.py:625} INFO - Processing file /opt/airflow/dags/example_twitter_dag.py for tasks to queue
[2021-11-18 10:40:54,967] {logging_mixin.py:109} INFO - [2021-11-18 10:40:54,967] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:40:55,031] {logging_mixin.py:109} INFO - [2021-11-18 10:40:55,026] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2021-11-18 10:40:55,089] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:40:55,118] {processor.py:171} INFO - Processing /opt/airflow/dags/example_twitter_dag.py took 0.191 seconds
[2021-11-18 10:41:25,275] {processor.py:163} INFO - Started process (PID=1576) to work on /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:41:25,279] {processor.py:625} INFO - Processing file /opt/airflow/dags/example_twitter_dag.py for tasks to queue
[2021-11-18 10:41:25,280] {logging_mixin.py:109} INFO - [2021-11-18 10:41:25,280] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:41:25,296] {logging_mixin.py:109} INFO - [2021-11-18 10:41:25,295] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2021-11-18 10:41:25,315] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:41:25,326] {processor.py:171} INFO - Processing /opt/airflow/dags/example_twitter_dag.py took 0.055 seconds
[2021-11-18 10:41:55,635] {processor.py:163} INFO - Started process (PID=1629) to work on /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:41:55,639] {processor.py:625} INFO - Processing file /opt/airflow/dags/example_twitter_dag.py for tasks to queue
[2021-11-18 10:41:55,640] {logging_mixin.py:109} INFO - [2021-11-18 10:41:55,640] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:41:55,667] {logging_mixin.py:109} INFO - [2021-11-18 10:41:55,663] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2021-11-18 10:41:55,690] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:41:55,700] {processor.py:171} INFO - Processing /opt/airflow/dags/example_twitter_dag.py took 0.069 seconds
[2021-11-18 10:42:26,093] {processor.py:163} INFO - Started process (PID=1688) to work on /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:42:26,097] {processor.py:625} INFO - Processing file /opt/airflow/dags/example_twitter_dag.py for tasks to queue
[2021-11-18 10:42:26,100] {logging_mixin.py:109} INFO - [2021-11-18 10:42:26,100] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:42:26,132] {logging_mixin.py:109} INFO - [2021-11-18 10:42:26,127] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2021-11-18 10:42:26,168] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:42:26,232] {processor.py:171} INFO - Processing /opt/airflow/dags/example_twitter_dag.py took 0.143 seconds
[2021-11-18 10:42:56,731] {processor.py:163} INFO - Started process (PID=1742) to work on /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:42:56,800] {processor.py:625} INFO - Processing file /opt/airflow/dags/example_twitter_dag.py for tasks to queue
[2021-11-18 10:42:56,805] {logging_mixin.py:109} INFO - [2021-11-18 10:42:56,805] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:42:56,896] {logging_mixin.py:109} INFO - [2021-11-18 10:42:56,880] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2021-11-18 10:42:56,978] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:42:57,078] {processor.py:171} INFO - Processing /opt/airflow/dags/example_twitter_dag.py took 0.376 seconds
[2021-11-18 10:43:27,194] {processor.py:163} INFO - Started process (PID=1796) to work on /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:43:27,199] {processor.py:625} INFO - Processing file /opt/airflow/dags/example_twitter_dag.py for tasks to queue
[2021-11-18 10:43:27,200] {logging_mixin.py:109} INFO - [2021-11-18 10:43:27,200] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:43:27,228] {logging_mixin.py:109} INFO - [2021-11-18 10:43:27,225] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2021-11-18 10:43:27,253] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:43:27,264] {processor.py:171} INFO - Processing /opt/airflow/dags/example_twitter_dag.py took 0.074 seconds
[2021-11-18 10:43:57,691] {processor.py:163} INFO - Started process (PID=1853) to work on /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:43:57,695] {processor.py:625} INFO - Processing file /opt/airflow/dags/example_twitter_dag.py for tasks to queue
[2021-11-18 10:43:57,697] {logging_mixin.py:109} INFO - [2021-11-18 10:43:57,696] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:43:57,715] {logging_mixin.py:109} INFO - [2021-11-18 10:43:57,712] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2021-11-18 10:43:57,739] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:43:57,753] {processor.py:171} INFO - Processing /opt/airflow/dags/example_twitter_dag.py took 0.072 seconds
[2021-11-18 10:44:28,108] {processor.py:163} INFO - Started process (PID=1919) to work on /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:44:28,113] {processor.py:625} INFO - Processing file /opt/airflow/dags/example_twitter_dag.py for tasks to queue
[2021-11-18 10:44:28,114] {logging_mixin.py:109} INFO - [2021-11-18 10:44:28,114] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:44:28,133] {logging_mixin.py:109} INFO - [2021-11-18 10:44:28,131] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2021-11-18 10:44:28,151] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:44:28,160] {processor.py:171} INFO - Processing /opt/airflow/dags/example_twitter_dag.py took 0.059 seconds
[2021-11-18 10:44:58,938] {processor.py:163} INFO - Started process (PID=1975) to work on /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:44:58,942] {processor.py:625} INFO - Processing file /opt/airflow/dags/example_twitter_dag.py for tasks to queue
[2021-11-18 10:44:58,947] {logging_mixin.py:109} INFO - [2021-11-18 10:44:58,947] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:44:58,973] {logging_mixin.py:109} INFO - [2021-11-18 10:44:58,970] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2021-11-18 10:44:58,991] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:44:59,008] {processor.py:171} INFO - Processing /opt/airflow/dags/example_twitter_dag.py took 0.080 seconds
[2021-11-18 10:45:29,319] {processor.py:163} INFO - Started process (PID=2030) to work on /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:45:29,322] {processor.py:625} INFO - Processing file /opt/airflow/dags/example_twitter_dag.py for tasks to queue
[2021-11-18 10:45:29,324] {logging_mixin.py:109} INFO - [2021-11-18 10:45:29,323] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:45:29,350] {logging_mixin.py:109} INFO - [2021-11-18 10:45:29,347] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2021-11-18 10:45:29,371] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:45:29,382] {processor.py:171} INFO - Processing /opt/airflow/dags/example_twitter_dag.py took 0.074 seconds
[2021-11-18 10:45:59,980] {processor.py:163} INFO - Started process (PID=2096) to work on /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:45:59,986] {processor.py:625} INFO - Processing file /opt/airflow/dags/example_twitter_dag.py for tasks to queue
[2021-11-18 10:45:59,990] {logging_mixin.py:109} INFO - [2021-11-18 10:45:59,990] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:46:00,040] {logging_mixin.py:109} INFO - [2021-11-18 10:46:00,029] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2021-11-18 10:46:00,076] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:46:00,092] {processor.py:171} INFO - Processing /opt/airflow/dags/example_twitter_dag.py took 0.119 seconds
[2021-11-18 10:46:30,662] {processor.py:163} INFO - Started process (PID=2151) to work on /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:46:30,666] {processor.py:625} INFO - Processing file /opt/airflow/dags/example_twitter_dag.py for tasks to queue
[2021-11-18 10:46:30,668] {logging_mixin.py:109} INFO - [2021-11-18 10:46:30,667] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:46:30,687] {logging_mixin.py:109} INFO - [2021-11-18 10:46:30,685] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2021-11-18 10:46:30,706] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:46:30,715] {processor.py:171} INFO - Processing /opt/airflow/dags/example_twitter_dag.py took 0.059 seconds
[2021-11-18 10:47:00,861] {processor.py:163} INFO - Started process (PID=2205) to work on /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:47:00,863] {processor.py:625} INFO - Processing file /opt/airflow/dags/example_twitter_dag.py for tasks to queue
[2021-11-18 10:47:00,865] {logging_mixin.py:109} INFO - [2021-11-18 10:47:00,865] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:47:00,885] {logging_mixin.py:109} INFO - [2021-11-18 10:47:00,883] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2021-11-18 10:47:00,903] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:47:00,912] {processor.py:171} INFO - Processing /opt/airflow/dags/example_twitter_dag.py took 0.055 seconds
[2021-11-18 10:47:30,985] {processor.py:163} INFO - Started process (PID=2263) to work on /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:47:30,987] {processor.py:625} INFO - Processing file /opt/airflow/dags/example_twitter_dag.py for tasks to queue
[2021-11-18 10:47:30,989] {logging_mixin.py:109} INFO - [2021-11-18 10:47:30,988] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:47:31,011] {logging_mixin.py:109} INFO - [2021-11-18 10:47:31,008] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2021-11-18 10:47:31,034] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:47:31,047] {processor.py:171} INFO - Processing /opt/airflow/dags/example_twitter_dag.py took 0.066 seconds
[2021-11-18 10:48:01,226] {processor.py:163} INFO - Started process (PID=2315) to work on /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:48:01,232] {processor.py:625} INFO - Processing file /opt/airflow/dags/example_twitter_dag.py for tasks to queue
[2021-11-18 10:48:01,237] {logging_mixin.py:109} INFO - [2021-11-18 10:48:01,236] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:48:01,276] {logging_mixin.py:109} INFO - [2021-11-18 10:48:01,272] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2021-11-18 10:48:01,297] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:48:01,308] {processor.py:171} INFO - Processing /opt/airflow/dags/example_twitter_dag.py took 0.092 seconds
[2021-11-18 10:48:31,489] {processor.py:163} INFO - Started process (PID=2370) to work on /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:48:31,501] {processor.py:625} INFO - Processing file /opt/airflow/dags/example_twitter_dag.py for tasks to queue
[2021-11-18 10:48:31,503] {logging_mixin.py:109} INFO - [2021-11-18 10:48:31,503] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:48:31,553] {logging_mixin.py:109} INFO - [2021-11-18 10:48:31,541] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2021-11-18 10:48:31,599] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:48:31,622] {processor.py:171} INFO - Processing /opt/airflow/dags/example_twitter_dag.py took 0.136 seconds
[2021-11-18 10:49:02,295] {processor.py:163} INFO - Started process (PID=2424) to work on /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:49:02,304] {processor.py:625} INFO - Processing file /opt/airflow/dags/example_twitter_dag.py for tasks to queue
[2021-11-18 10:49:02,315] {logging_mixin.py:109} INFO - [2021-11-18 10:49:02,308] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:49:02,372] {logging_mixin.py:109} INFO - [2021-11-18 10:49:02,348] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2021-11-18 10:49:02,442] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:49:02,449] {processor.py:171} INFO - Processing /opt/airflow/dags/example_twitter_dag.py took 0.159 seconds
[2021-11-18 10:49:32,712] {processor.py:163} INFO - Started process (PID=2469) to work on /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:49:32,714] {processor.py:625} INFO - Processing file /opt/airflow/dags/example_twitter_dag.py for tasks to queue
[2021-11-18 10:49:32,716] {logging_mixin.py:109} INFO - [2021-11-18 10:49:32,716] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:49:32,747] {logging_mixin.py:109} INFO - [2021-11-18 10:49:32,740] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2021-11-18 10:49:32,776] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:49:32,788] {processor.py:171} INFO - Processing /opt/airflow/dags/example_twitter_dag.py took 0.080 seconds
[2021-11-18 10:50:13,702] {processor.py:163} INFO - Started process (PID=2525) to work on /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:50:13,751] {processor.py:625} INFO - Processing file /opt/airflow/dags/example_twitter_dag.py for tasks to queue
[2021-11-18 10:50:13,768] {logging_mixin.py:109} INFO - [2021-11-18 10:50:13,768] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:50:14,034] {logging_mixin.py:109} INFO - [2021-11-18 10:50:14,005] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2021-11-18 10:50:14,207] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:50:14,278] {processor.py:171} INFO - Processing /opt/airflow/dags/example_twitter_dag.py took 0.639 seconds
[2021-11-18 10:50:44,918] {processor.py:163} INFO - Started process (PID=2570) to work on /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:50:44,923] {processor.py:625} INFO - Processing file /opt/airflow/dags/example_twitter_dag.py for tasks to queue
[2021-11-18 10:50:44,926] {logging_mixin.py:109} INFO - [2021-11-18 10:50:44,926] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:50:44,967] {logging_mixin.py:109} INFO - [2021-11-18 10:50:44,963] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2021-11-18 10:50:45,007] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:50:45,029] {processor.py:171} INFO - Processing /opt/airflow/dags/example_twitter_dag.py took 0.125 seconds
[2021-11-18 10:51:15,784] {processor.py:163} INFO - Started process (PID=2625) to work on /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:51:15,800] {processor.py:625} INFO - Processing file /opt/airflow/dags/example_twitter_dag.py for tasks to queue
[2021-11-18 10:51:15,802] {logging_mixin.py:109} INFO - [2021-11-18 10:51:15,802] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:51:15,820] {logging_mixin.py:109} INFO - [2021-11-18 10:51:15,817] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2021-11-18 10:51:15,837] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:51:15,847] {processor.py:171} INFO - Processing /opt/airflow/dags/example_twitter_dag.py took 0.067 seconds
[2021-11-18 10:51:46,304] {processor.py:163} INFO - Started process (PID=2683) to work on /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:51:46,308] {processor.py:625} INFO - Processing file /opt/airflow/dags/example_twitter_dag.py for tasks to queue
[2021-11-18 10:51:46,312] {logging_mixin.py:109} INFO - [2021-11-18 10:51:46,311] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:51:46,347] {logging_mixin.py:109} INFO - [2021-11-18 10:51:46,345] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2021-11-18 10:51:46,367] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:51:46,379] {processor.py:171} INFO - Processing /opt/airflow/dags/example_twitter_dag.py took 0.089 seconds
[2021-11-18 10:52:16,688] {processor.py:163} INFO - Started process (PID=2738) to work on /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:52:16,692] {processor.py:625} INFO - Processing file /opt/airflow/dags/example_twitter_dag.py for tasks to queue
[2021-11-18 10:52:16,695] {logging_mixin.py:109} INFO - [2021-11-18 10:52:16,694] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:52:16,712] {logging_mixin.py:109} INFO - [2021-11-18 10:52:16,710] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2021-11-18 10:52:16,738] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:52:16,747] {processor.py:171} INFO - Processing /opt/airflow/dags/example_twitter_dag.py took 0.066 seconds
[2021-11-18 10:52:49,941] {processor.py:163} INFO - Started process (PID=2802) to work on /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:52:49,976] {processor.py:625} INFO - Processing file /opt/airflow/dags/example_twitter_dag.py for tasks to queue
[2021-11-18 10:52:49,991] {logging_mixin.py:109} INFO - [2021-11-18 10:52:49,990] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:52:50,382] {logging_mixin.py:109} INFO - [2021-11-18 10:52:50,342] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2021-11-18 10:52:50,525] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:52:50,633] {processor.py:171} INFO - Processing /opt/airflow/dags/example_twitter_dag.py took 0.730 seconds
[2021-11-18 10:53:25,583] {processor.py:163} INFO - Started process (PID=2842) to work on /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:53:25,639] {processor.py:625} INFO - Processing file /opt/airflow/dags/example_twitter_dag.py for tasks to queue
[2021-11-18 10:53:25,668] {logging_mixin.py:109} INFO - [2021-11-18 10:53:25,667] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:53:25,788] {logging_mixin.py:109} INFO - [2021-11-18 10:53:25,772] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2021-11-18 10:53:25,945] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:53:26,110] {processor.py:171} INFO - Processing /opt/airflow/dags/example_twitter_dag.py took 0.576 seconds
[2021-11-18 10:53:57,058] {processor.py:163} INFO - Started process (PID=2896) to work on /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:53:57,063] {processor.py:625} INFO - Processing file /opt/airflow/dags/example_twitter_dag.py for tasks to queue
[2021-11-18 10:53:57,066] {logging_mixin.py:109} INFO - [2021-11-18 10:53:57,066] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:53:57,106] {logging_mixin.py:109} INFO - [2021-11-18 10:53:57,102] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2021-11-18 10:53:57,136] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:53:57,148] {processor.py:171} INFO - Processing /opt/airflow/dags/example_twitter_dag.py took 0.096 seconds
[2021-11-18 10:54:27,452] {processor.py:163} INFO - Started process (PID=2954) to work on /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:54:27,454] {processor.py:625} INFO - Processing file /opt/airflow/dags/example_twitter_dag.py for tasks to queue
[2021-11-18 10:54:27,456] {logging_mixin.py:109} INFO - [2021-11-18 10:54:27,456] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:54:27,474] {logging_mixin.py:109} INFO - [2021-11-18 10:54:27,472] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2021-11-18 10:54:27,495] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:54:27,503] {processor.py:171} INFO - Processing /opt/airflow/dags/example_twitter_dag.py took 0.055 seconds
[2021-11-18 10:54:57,775] {processor.py:163} INFO - Started process (PID=3010) to work on /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:54:57,780] {processor.py:625} INFO - Processing file /opt/airflow/dags/example_twitter_dag.py for tasks to queue
[2021-11-18 10:54:57,783] {logging_mixin.py:109} INFO - [2021-11-18 10:54:57,782] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:54:57,814] {logging_mixin.py:109} INFO - [2021-11-18 10:54:57,809] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2021-11-18 10:54:57,847] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:54:57,855] {processor.py:171} INFO - Processing /opt/airflow/dags/example_twitter_dag.py took 0.086 seconds
[2021-11-18 10:55:28,519] {processor.py:163} INFO - Started process (PID=3064) to work on /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:55:28,522] {processor.py:625} INFO - Processing file /opt/airflow/dags/example_twitter_dag.py for tasks to queue
[2021-11-18 10:55:28,525] {logging_mixin.py:109} INFO - [2021-11-18 10:55:28,524] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:55:28,555] {logging_mixin.py:109} INFO - [2021-11-18 10:55:28,551] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2021-11-18 10:55:28,601] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:55:28,614] {processor.py:171} INFO - Processing /opt/airflow/dags/example_twitter_dag.py took 0.103 seconds
[2021-11-18 10:55:59,134] {processor.py:163} INFO - Started process (PID=3121) to work on /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:55:59,137] {processor.py:625} INFO - Processing file /opt/airflow/dags/example_twitter_dag.py for tasks to queue
[2021-11-18 10:55:59,139] {logging_mixin.py:109} INFO - [2021-11-18 10:55:59,139] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:55:59,163] {logging_mixin.py:109} INFO - [2021-11-18 10:55:59,160] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2021-11-18 10:55:59,182] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:55:59,193] {processor.py:171} INFO - Processing /opt/airflow/dags/example_twitter_dag.py took 0.065 seconds
[2021-11-18 10:56:29,443] {processor.py:163} INFO - Started process (PID=3184) to work on /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:56:29,445] {processor.py:625} INFO - Processing file /opt/airflow/dags/example_twitter_dag.py for tasks to queue
[2021-11-18 10:56:29,447] {logging_mixin.py:109} INFO - [2021-11-18 10:56:29,447] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:56:29,463] {logging_mixin.py:109} INFO - [2021-11-18 10:56:29,461] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2021-11-18 10:56:29,491] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:56:29,501] {processor.py:171} INFO - Processing /opt/airflow/dags/example_twitter_dag.py took 0.061 seconds
[2021-11-18 10:56:59,545] {processor.py:163} INFO - Started process (PID=3240) to work on /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:56:59,547] {processor.py:625} INFO - Processing file /opt/airflow/dags/example_twitter_dag.py for tasks to queue
[2021-11-18 10:56:59,549] {logging_mixin.py:109} INFO - [2021-11-18 10:56:59,549] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:56:59,566] {logging_mixin.py:109} INFO - [2021-11-18 10:56:59,563] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2021-11-18 10:56:59,586] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:56:59,593] {processor.py:171} INFO - Processing /opt/airflow/dags/example_twitter_dag.py took 0.052 seconds
[2021-11-18 10:57:29,744] {processor.py:163} INFO - Started process (PID=3292) to work on /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:57:29,753] {processor.py:625} INFO - Processing file /opt/airflow/dags/example_twitter_dag.py for tasks to queue
[2021-11-18 10:57:29,755] {logging_mixin.py:109} INFO - [2021-11-18 10:57:29,754] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:57:29,793] {logging_mixin.py:109} INFO - [2021-11-18 10:57:29,791] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2021-11-18 10:57:29,826] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:57:29,839] {processor.py:171} INFO - Processing /opt/airflow/dags/example_twitter_dag.py took 0.100 seconds
[2021-11-18 10:58:00,225] {processor.py:163} INFO - Started process (PID=3345) to work on /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:58:00,229] {processor.py:625} INFO - Processing file /opt/airflow/dags/example_twitter_dag.py for tasks to queue
[2021-11-18 10:58:00,231] {logging_mixin.py:109} INFO - [2021-11-18 10:58:00,231] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:58:00,251] {logging_mixin.py:109} INFO - [2021-11-18 10:58:00,249] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2021-11-18 10:58:00,271] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:58:00,284] {processor.py:171} INFO - Processing /opt/airflow/dags/example_twitter_dag.py took 0.065 seconds
[2021-11-18 10:58:30,796] {processor.py:163} INFO - Started process (PID=3411) to work on /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:58:30,799] {processor.py:625} INFO - Processing file /opt/airflow/dags/example_twitter_dag.py for tasks to queue
[2021-11-18 10:58:30,808] {logging_mixin.py:109} INFO - [2021-11-18 10:58:30,808] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:58:30,857] {logging_mixin.py:109} INFO - [2021-11-18 10:58:30,851] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2021-11-18 10:58:30,904] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:58:30,947] {processor.py:171} INFO - Processing /opt/airflow/dags/example_twitter_dag.py took 0.159 seconds
[2021-11-18 10:59:01,208] {processor.py:163} INFO - Started process (PID=3467) to work on /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:59:01,210] {processor.py:625} INFO - Processing file /opt/airflow/dags/example_twitter_dag.py for tasks to queue
[2021-11-18 10:59:01,213] {logging_mixin.py:109} INFO - [2021-11-18 10:59:01,212] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:59:01,233] {logging_mixin.py:109} INFO - [2021-11-18 10:59:01,231] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2021-11-18 10:59:01,278] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:59:01,291] {processor.py:171} INFO - Processing /opt/airflow/dags/example_twitter_dag.py took 0.092 seconds
[2021-11-18 10:59:31,671] {processor.py:163} INFO - Started process (PID=3523) to work on /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:59:31,674] {processor.py:625} INFO - Processing file /opt/airflow/dags/example_twitter_dag.py for tasks to queue
[2021-11-18 10:59:31,676] {logging_mixin.py:109} INFO - [2021-11-18 10:59:31,676] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:59:31,705] {logging_mixin.py:109} INFO - [2021-11-18 10:59:31,699] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2021-11-18 10:59:31,740] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 10:59:31,758] {processor.py:171} INFO - Processing /opt/airflow/dags/example_twitter_dag.py took 0.094 seconds
[2021-11-18 11:00:01,894] {processor.py:163} INFO - Started process (PID=3587) to work on /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 11:00:01,905] {processor.py:625} INFO - Processing file /opt/airflow/dags/example_twitter_dag.py for tasks to queue
[2021-11-18 11:00:01,909] {logging_mixin.py:109} INFO - [2021-11-18 11:00:01,908] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 11:00:01,948] {logging_mixin.py:109} INFO - [2021-11-18 11:00:01,945] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2021-11-18 11:00:01,987] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 11:00:02,001] {processor.py:171} INFO - Processing /opt/airflow/dags/example_twitter_dag.py took 0.119 seconds
[2021-11-18 11:00:32,600] {processor.py:163} INFO - Started process (PID=3642) to work on /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 11:00:32,603] {processor.py:625} INFO - Processing file /opt/airflow/dags/example_twitter_dag.py for tasks to queue
[2021-11-18 11:00:32,614] {logging_mixin.py:109} INFO - [2021-11-18 11:00:32,614] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 11:00:32,692] {logging_mixin.py:109} INFO - [2021-11-18 11:00:32,676] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2021-11-18 11:00:32,751] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 11:00:32,768] {processor.py:171} INFO - Processing /opt/airflow/dags/example_twitter_dag.py took 0.182 seconds
[2021-11-18 11:01:02,863] {processor.py:163} INFO - Started process (PID=3698) to work on /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 11:01:02,865] {processor.py:625} INFO - Processing file /opt/airflow/dags/example_twitter_dag.py for tasks to queue
[2021-11-18 11:01:02,866] {logging_mixin.py:109} INFO - [2021-11-18 11:01:02,866] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 11:01:02,885] {logging_mixin.py:109} INFO - [2021-11-18 11:01:02,883] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2021-11-18 11:01:02,903] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 11:01:02,913] {processor.py:171} INFO - Processing /opt/airflow/dags/example_twitter_dag.py took 0.054 seconds
[2021-11-18 11:01:33,268] {processor.py:163} INFO - Started process (PID=3765) to work on /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 11:01:33,271] {processor.py:625} INFO - Processing file /opt/airflow/dags/example_twitter_dag.py for tasks to queue
[2021-11-18 11:01:33,272] {logging_mixin.py:109} INFO - [2021-11-18 11:01:33,272] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 11:01:33,298] {logging_mixin.py:109} INFO - [2021-11-18 11:01:33,295] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2021-11-18 11:01:33,323] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 11:01:33,338] {processor.py:171} INFO - Processing /opt/airflow/dags/example_twitter_dag.py took 0.074 seconds
[2021-11-18 11:02:03,460] {processor.py:163} INFO - Started process (PID=3821) to work on /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 11:02:03,462] {processor.py:625} INFO - Processing file /opt/airflow/dags/example_twitter_dag.py for tasks to queue
[2021-11-18 11:02:03,463] {logging_mixin.py:109} INFO - [2021-11-18 11:02:03,463] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 11:02:03,508] {logging_mixin.py:109} INFO - [2021-11-18 11:02:03,494] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2021-11-18 11:02:03,543] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 11:02:03,566] {processor.py:171} INFO - Processing /opt/airflow/dags/example_twitter_dag.py took 0.119 seconds
[2021-11-18 11:02:34,032] {processor.py:163} INFO - Started process (PID=3884) to work on /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 11:02:34,035] {processor.py:625} INFO - Processing file /opt/airflow/dags/example_twitter_dag.py for tasks to queue
[2021-11-18 11:02:34,037] {logging_mixin.py:109} INFO - [2021-11-18 11:02:34,037] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 11:02:34,057] {logging_mixin.py:109} INFO - [2021-11-18 11:02:34,054] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2021-11-18 11:02:34,075] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 11:02:34,083] {processor.py:171} INFO - Processing /opt/airflow/dags/example_twitter_dag.py took 0.057 seconds
[2021-11-18 11:03:04,146] {processor.py:163} INFO - Started process (PID=3940) to work on /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 11:03:04,150] {processor.py:625} INFO - Processing file /opt/airflow/dags/example_twitter_dag.py for tasks to queue
[2021-11-18 11:03:04,151] {logging_mixin.py:109} INFO - [2021-11-18 11:03:04,151] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 11:03:04,167] {logging_mixin.py:109} INFO - [2021-11-18 11:03:04,164] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2021-11-18 11:03:04,185] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 11:03:04,193] {processor.py:171} INFO - Processing /opt/airflow/dags/example_twitter_dag.py took 0.051 seconds
[2021-11-18 11:03:34,555] {processor.py:163} INFO - Started process (PID=3996) to work on /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 11:03:34,557] {processor.py:625} INFO - Processing file /opt/airflow/dags/example_twitter_dag.py for tasks to queue
[2021-11-18 11:03:34,558] {logging_mixin.py:109} INFO - [2021-11-18 11:03:34,558] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 11:03:34,577] {logging_mixin.py:109} INFO - [2021-11-18 11:03:34,575] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2021-11-18 11:03:34,597] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 11:03:34,608] {processor.py:171} INFO - Processing /opt/airflow/dags/example_twitter_dag.py took 0.058 seconds
[2021-11-18 11:04:04,809] {processor.py:163} INFO - Started process (PID=4061) to work on /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 11:04:04,812] {processor.py:625} INFO - Processing file /opt/airflow/dags/example_twitter_dag.py for tasks to queue
[2021-11-18 11:04:04,813] {logging_mixin.py:109} INFO - [2021-11-18 11:04:04,813] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 11:04:04,829] {logging_mixin.py:109} INFO - [2021-11-18 11:04:04,826] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2021-11-18 11:04:04,844] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 11:04:04,853] {processor.py:171} INFO - Processing /opt/airflow/dags/example_twitter_dag.py took 0.048 seconds
[2021-11-18 11:04:35,228] {processor.py:163} INFO - Started process (PID=4119) to work on /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 11:04:35,232] {processor.py:625} INFO - Processing file /opt/airflow/dags/example_twitter_dag.py for tasks to queue
[2021-11-18 11:04:35,233] {logging_mixin.py:109} INFO - [2021-11-18 11:04:35,233] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 11:04:35,248] {logging_mixin.py:109} INFO - [2021-11-18 11:04:35,246] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2021-11-18 11:04:35,264] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 11:04:35,271] {processor.py:171} INFO - Processing /opt/airflow/dags/example_twitter_dag.py took 0.047 seconds
[2021-11-18 11:05:05,394] {processor.py:163} INFO - Started process (PID=4185) to work on /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 11:05:05,398] {processor.py:625} INFO - Processing file /opt/airflow/dags/example_twitter_dag.py for tasks to queue
[2021-11-18 11:05:05,400] {logging_mixin.py:109} INFO - [2021-11-18 11:05:05,400] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 11:05:05,417] {logging_mixin.py:109} INFO - [2021-11-18 11:05:05,415] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2021-11-18 11:05:05,433] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 11:05:05,442] {processor.py:171} INFO - Processing /opt/airflow/dags/example_twitter_dag.py took 0.052 seconds
[2021-11-18 11:05:35,599] {processor.py:163} INFO - Started process (PID=4240) to work on /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 11:05:35,604] {processor.py:625} INFO - Processing file /opt/airflow/dags/example_twitter_dag.py for tasks to queue
[2021-11-18 11:05:35,606] {logging_mixin.py:109} INFO - [2021-11-18 11:05:35,605] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 11:05:35,657] {logging_mixin.py:109} INFO - [2021-11-18 11:05:35,654] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2021-11-18 11:05:35,687] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 11:05:35,700] {processor.py:171} INFO - Processing /opt/airflow/dags/example_twitter_dag.py took 0.109 seconds
[2021-11-18 11:06:06,562] {processor.py:163} INFO - Started process (PID=4299) to work on /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 11:06:06,564] {processor.py:625} INFO - Processing file /opt/airflow/dags/example_twitter_dag.py for tasks to queue
[2021-11-18 11:06:06,566] {logging_mixin.py:109} INFO - [2021-11-18 11:06:06,566] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 11:06:06,611] {logging_mixin.py:109} INFO - [2021-11-18 11:06:06,606] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2021-11-18 11:06:06,641] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 11:06:06,658] {processor.py:171} INFO - Processing /opt/airflow/dags/example_twitter_dag.py took 0.100 seconds
[2021-11-18 11:06:37,498] {processor.py:163} INFO - Started process (PID=4363) to work on /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 11:06:37,514] {processor.py:625} INFO - Processing file /opt/airflow/dags/example_twitter_dag.py for tasks to queue
[2021-11-18 11:06:37,518] {logging_mixin.py:109} INFO - [2021-11-18 11:06:37,518] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 11:06:37,582] {logging_mixin.py:109} INFO - [2021-11-18 11:06:37,580] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2021-11-18 11:06:37,638] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 11:06:37,665] {processor.py:171} INFO - Processing /opt/airflow/dags/example_twitter_dag.py took 0.180 seconds
[2021-11-18 11:07:09,423] {processor.py:163} INFO - Started process (PID=4417) to work on /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 11:07:09,506] {processor.py:625} INFO - Processing file /opt/airflow/dags/example_twitter_dag.py for tasks to queue
[2021-11-18 11:07:09,552] {logging_mixin.py:109} INFO - [2021-11-18 11:07:09,552] {dagbag.py:500} INFO - Filling up the DagBag from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 11:07:10,419] {logging_mixin.py:109} INFO - [2021-11-18 11:07:10,385] {dagbag.py:334} ERROR - Failed to import: /opt/airflow/dags/example_twitter_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 331, in _load_modules_from_file
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/example_twitter_dag.py", line 34, in <module>
    from airflow.operators.hive_operator import HiveOperator
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/hive_operator.py", line 22, in <module>
    from airflow.providers.apache.hive.operators.hive import HiveOperator  # noqa
ModuleNotFoundError: No module named 'airflow.providers.apache'
[2021-11-18 11:07:10,800] {processor.py:639} WARNING - No viable dags retrieved from /opt/airflow/dags/example_twitter_dag.py
[2021-11-18 11:07:11,132] {processor.py:171} INFO - Processing /opt/airflow/dags/example_twitter_dag.py took 1.813 seconds
